kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80     # ingress HTTP
      - containerPort: 30443
        hostPort: 443    # ingress HTTPS
      - containerPort: 30032
        hostPort: 30032  # plex (non-HTTP)
      - containerPort: 30033
        hostPort: 30033  # jellyfin (non-HTTP)
  - role: worker
  - role: worker
