apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: nextcloud-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          env:
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "changeme"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "100.122.254.107"
            - name: OVERWRITEPROTOCOL
              value: "http"
            - name: OVERWRITEHOST
              value: "100.122.254.107:3011"
            - name: TRUSTED_PROXIES
              value: "0.0.0.0/0"
          volumeMounts:
            - name: data
              mountPath: /var/www/html
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: media
spec:
  selector:
    app: nextcloud
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
